name: Generate GitHub Readme Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Top Languages Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: "username=smartinez437&layout=compact&theme=tokyonight&hide_border=true"
          path: profile/top-langs.svg
          token: ${{ secrets.GH_PAT }}

      - name: Commit and Push SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/top-langs.svg
          git diff --staged --quiet || git commit -m "update top-langs stat card"
          git push
